remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-cayman

github:
  is_project_page: false

title: Colloqium Joost-Pieter Katoen
#description: Celebration event on the occasion of Joost-Pieter's 60th birthday
show_downloads: false
logo: logo.jpeg