remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-cayman

github:
  is_project_page: false

title: Colloqium Joost-Pieter Katoen
description: Joost-Pieter in Logic Lane [source](https://en.wikipedia.org/wiki/Joost-Pieter_Katoen)
show_downloads: false
logo: logo.jpeg